#python susy-interface/plotmaker.py sos2l16 dyLow16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 33.2 --make bkgs --plots all -o AR --flags "--perBin -X twoTight -E oneNotTight --sP map.*_2l" -p "fakes_matched_.*" -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8
python susy-interface/plotmaker.py sos2l16 dyMed16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 35.9 --make bkgs --plots all -o AR --flags "--perBin -X twoTight -E oneNotTight --sP map.*_2l" -p "fakes_matched_.*" -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8

python susy-interface/plotmaker.py sos2l16 ttLow16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 33.2 --make bkgs --plots all -o AR --flags "--perBin -X twoTight -E oneNotTight --sP map.*_2l" -p "fakes_matched_.*" -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8
python susy-interface/plotmaker.py sos2l16 ttMed16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 35.9 --make bkgs --plots all -o AR --flags "--perBin -X twoTight -E oneNotTight --sP map.*_2l" -p "fakes_matched_.*" -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8

python susy-interface/plotmaker.py sos2l16 vvLow16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 33.2 --make bkgs --plots all -o AR --flags "--perBin -X twoTight -E oneNotTight --sP map.*_2l" -p "fakes_matched_.*"  -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8
python susy-interface/plotmaker.py sos2l16 vvMed16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 35.9 --make bkgs --plots all -o AR --flags "--perBin -X twoTight -E oneNotTight --sP map.*_2l" -p "fakes_matched_.*"  -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8

python susy-interface/plotmaker.py sos3l16 wzMin16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 35.9 --make bkgs --plots all -o AR --flags "--perBin -X threeTight -E oneNotTight --sP map.*_3l" -p "fakes_matched_.*"  -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8
python susy-interface/plotmaker.py sos3l16 wzLow16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 35.9 --make bkgs --plots all -o AR --flags "--perBin -X threeTight -E oneNotTight --sP map.*_3l" -p "fakes_matched_.*"  -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8
python susy-interface/plotmaker.py sos3l16 wzMed16 "/data1/cheidegg/trees_SOS_010217_skimmed" /afs/cern.ch/user/c/cheidegg/www/heppy/2018-07-21_sos16_fullstatusMPFR -l 35.9 --make bkgs --plots all -o AR --flags "--perBin -X threeTight -E oneNotTight --sP map.*_3l" -p "fakes_matched_.*"  -W 'wBG' --plot susy-sos-v1/plots_mpfr.txt -j 8
